unbind C-b
set -g prefix C-g
bind-key C-g send-prefix

unbind r
bind r source-file ~/.config/tmux/tmux.conf

# Window splitting and maximization
unbind %
bind | split-window -h
unbind '"'
bind - split-window -v
bind -r m resize-pane -Z

# Start counting pane and window number at 1
set -g base-index 1
setw -g pane-base-index 1

# Pane resizing
bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r l resize-pane -R 5
bind -r h resize-pane -L 5

# Mouse
set -g mouse on

# Vim key bindings
setw -g mode-keys vi

bind-key -T copy-mode-vi 'v' send -X begin-selection # start selecting text with "v"
bind-key -T copy-mode-vi 'y' send -X copy-selection # copy text with "y"

unbind -T copy-mode-vi MouseDragEnd1Pane # don't exit copy mode when dragging with mouse

# remove delay for exiting insert mode with ESC in Neovim
set -sg escape-time 10

# enable shift+enter for claude
set -s extended-keys on
set -as terminal-features 'xterm*:extkeys'

set -g set-clipboard on          # use system clipboard
set -g status-position top       # macOS / darwin style
set -g pane-active-border-style 'fg=magenta,bg=default'
set -g pane-border-style 'fg=brightblack,bg=default'

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin "arcticicestudio/nord-tmux"
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'omerxx/tmux-floax'

set -g @dracula-show-powerline true
set -g @dracula-fixed-location "Sooke, BC"
set -g @dracula-plugins "weather"
set -g @dracula-show-flags true
set -g @dracula-show-left-icon session

set -g @floax-width '80%'
set -g @floax-height '80%'
set -g @floax-border-color 'magenta'
set -g @floax-text-color 'blue'
set -g @floax-bind 'p'
set -g @floax-change-path 'true'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'

# Override nord status-right to remove date and time
set -g status-right "#{prefix_highlight}#[fg=cyan,bg=black,nobold,noitalics,nounderscore]#[fg=black,bg=cyan,bold] #H "
